apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: web
    version: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      version: "1"
  template:
    metadata:
      labels:
        app: web
        version: "1"
    spec:
      containers:
        - name: web
          image: nginx:1.9.15
          imagePullPolicy: IfNotPresent
          name: nginx