version: "3.6"
services:
  app:
    # AWS ECR image
    image: 777216051792.dkr.ecr.us-east-1.amazonaws.com/cooperhewitt/museum-project:2.1-20181009
    command: development
    extra_hosts:
      - "bill:172.21.34.207"
      - "tmsdb:160.111.103.117"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.5"
          memory: 250M
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - type: volume
        source: media
        target: /root/project/media
      - type: volume
        source: static
        target: /root/project/static
      # bind mount to try latest code during development
      # the image should contain the final production version
      - type: bind
        source: ../django/project
        target: /root/project
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /usr/local/museum/tms-images
        target: /usr/local/museum/tms-images
    environment:
      - DEBUG=1
      - REDIS_HOST=redis
    secrets:
      - config.yaml
  database:
    # will use RDS for production
    image: postgres:10.4
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: volume
        source: database
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    secrets:
      - db_user
      - db_password
    environment:
      - POSTGRES_DB=db1
      - POSTGRES_USER_FILE=/run/secrets/db_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
  redis:
    image: redis:4.0.10
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
volumes:
  media:
  static:
  database:
secrets:
  config.yaml:
    file: config.yaml
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt