apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: database-replicaset
  labels:
    app: mysql-database
    version: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-database
      version: "1"
  template:
    metadata:
      labels:
        app: mysql-database
        version: "1"
    spec:
      containers:
        - name: mysql-database
          image: "mysql:5.7.17"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "secret"
          livenessProbe:
            tcpSocket:
              port: 3306
