apiVersion: v1
kind: Pod
metadata:
  name: kuard-config-yaml
spec:
  containers:
    - name: kuard-config-yaml
      image: gcr.io/kuar-demo/kuard-amd64:1
      imagePullPolicy: Always
      volumeMounts:
      - name: config
        mountPath: "/secrets"
        readOnly: true
  volumes:
    - name: config
      secret:
        secretName: config.yaml

