version: '2'

services:
  db2:
    container_name: db2
    hostname: db2
    image: "postgres:9.4"
    restart: always
    environment:
      - POSTGRES_USER=user2
      - POSTGRES_PASSWORD=user_secret
      - POSTGRES_DB=db2

  redis2:
    container_name: redis2
    hostname: redis2
    image: "redis:3.2.6"
    restart: always

  app2-dev:
    container_name: app2-dev
    hostname: app2-dev
    image: "alexisbellido/python:3.5.2-slim"
    restart: always
    environment:
      - SETTINGS_MODULE=locals3
      - POSTGRES_USER=user2
      - POSTGRES_PASSWORD=user_secret
      - POSTGRES_DB=db2
      - POSTGRES_HOST=db2
      - PROJECT_NAME=zinibu
    command: development
    ports:
      - "40001:8000"
    volumes:
      - /home/alexis/mydocker/zinibu:/root/zinibu
      - /home/alexis/mydocker/djapps:/root/djapps
    depends_on:
      - db2

  app2:
    container_name: app2
    hostname: app2
    image: "alexisbellido/python:3.5.2-slim"
    restart: always
    environment:
      - SETTINGS_MODULE=locals3
      - POSTGRES_USER=user2
      - POSTGRES_PASSWORD=user_secret
      - POSTGRES_DB=db2
      - POSTGRES_HOST=db2
      - REDIS_HOST=redis2
      - REDIS_PORT=6379
      - PROJECT_NAME=zinibu
    command: production
    ports:
      - "40011:8000"
    volumes:
      - /home/alexis/mydocker/zinibu:/root/zinibu
      - /home/alexis/mydocker/djapps:/root/djapps
    depends_on:
      - db2
      - redis2

  web2:
    container_name: web2
    hostname: web2
    image: "alexisbellido/nginx:1.10.2"
    restart: always
    environment:
      - APP_HOST=app2-dev
      - APP_PORT=8000
      - PROJECT_NAME=zinibu
    ports:
      - "40002:80"
    volumes:
      - /home/alexis/mydocker/zinibu:/usr/share/nginx/zinibu
    depends_on:
      - app2-dev

  cache2:
    container_name: cache2
    hostname: cache2
    image: "alexisbellido/varnish:4.1"
    restart: always
    environment:
      - WEB_HOST=web2
      - WEB_PORT=80
      - DOMAIN_NAME=example.com
    ports:
      - "40003:83"
    depends_on:
      - web2

  lb2:
    container_name: lb2
    hostname: lb2
    image: "alexisbellido/haproxy:1.6.10"
    restart: always
    volumes:
      - /home/alexis/mydocker/dockerize-django/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - "40004:80"
      - "40005:443"
      - "40006:8998"
    depends_on:
      - cache2
