apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4=
  password: c2VjcmV0
---
apiVersion: v1
kind: Pod
metadata:
  name: kuard-with-secret
spec:
  containers:
    - name: kuard-with-secret
      image: gcr.io/kuar-demo/kuard-amd64:1
      imagePullPolicy: Always
      volumeMounts:
      - name: credentials
        mountPath: "/secrets"
        readOnly: true
  volumes:
    - name: credentials
      secret:
        secretName: my-secret

