version: "3.6"
services:
  web:
    image: 'alexisbellido/django:2.0.5'
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8001:8000"