production:
  mysql:
    host: 1.2.3.4
    database: livedb
    username: root
    password: verysecret
local:
  mysql:
    host: 127.0.0.1
    database: localdb
    username: root
    password: secret
